### ISSUE TITLE
Example - Missing component in tasks

### ISSUE THREAD

**Issue by zpf0117b2** [Institute4FutureHealth/CHA#5]
Hi,

In the example you wrote:

`from tasks.playwright.utils import create_sync_playwright_browser`

However, I didn't see the playwright function in the tasks/ folder, which might cause
```
Traceback (most recent call last):
  File "/home/ics-home/opencha/opencha-foodkg/CHA/foodkg_opencha.py", line 2, in <module>
    from tasks.playwright.utils import create_sync_playwright_browser
ModuleNotFoundError: No module named 'tasks.playwright'
```

Where can we find it? Or is it from other source?

**Comment by TheMadSan** [comment]
Hello,

I believe the import statement was an example assuming a custom module setup that is not included in the repository. However, to achieve similar functionality without relying on a custom module, you can use the Playwright library directly.

Below is a revised example that you can use to create a synchronous Playwright browser instance without needing any additional custom code:

**Ensure Playwright is installed**:
```
pip install playwright
playwright install
```
**We can use the following snippet to create a synchronous playwright browser**:
```
from playwright.sync_api import sync_playwright

def create_sync_playwright_browser():
    playwright = sync_playwright().start()
    browser = playwright.chromium.launch()
    return browser

# Create the synchronous browser
sync_browser = create_sync_playwright_browser()
```
I hope this helps! Thank you!

**Comment by Mahyar12** [comment]
We have fixed the examples to follow our new changes. The problem was that we modified playwright implementation inside tasks to make it independent from openCHA class instantiation.
